"""Alembic-style revision to create core tables: sprites, user_sprites, trade_listings, trade_offers.

This file is a standalone SQLAlchemy/Alembic-like migration file. If you use Alembic, you can copy the operations into an Alembic autogenerated revision.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_create_core_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'sprites',
        sa.Column('id', sa.Text(), primary_key=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('rarity', sa.Text()),
        sa.Column('type', sa.Text()),
        sa.Column('power', sa.Text()),
        sa.Column('color', sa.Text()),
        sa.Column('images', sa.JSON()),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
    )

    op.create_table(
        'user_sprites',
        sa.Column('id', sa.Text(), primary_key=True),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('sprite_id', sa.Text(), sa.ForeignKey('sprites.id')),
        sa.Column('have', sa.Boolean(), server_default=sa.text('true')),
        sa.Column('count', sa.Integer(), server_default='1'),
        sa.Column('mastery', sa.Integer()),
        sa.Column('variant', sa.Text()),
        sa.Column('public', sa.Boolean(), server_default=sa.text('true')),
        sa.Column('notes', sa.Text()),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
    )

    op.create_table(
        'trade_listings',
        sa.Column('id', sa.Text(), primary_key=True),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('title', sa.Text()),
        sa.Column('offered', sa.JSON()),
        sa.Column('wanted', sa.JSON()),
        sa.Column('contact_username', sa.Text()),
        sa.Column('status', sa.Text(), server_default=sa.text("'open'")),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
    )

    op.create_table(
        'trade_offers',
        sa.Column('id', sa.Text(), primary_key=True),
        sa.Column('listing_id', sa.Text(), sa.ForeignKey('trade_listings.id')),
        sa.Column('from_user_id', sa.Text()),
        sa.Column('offered', sa.JSON()),
        sa.Column('message', sa.Text()),
        sa.Column('status', sa.Text(), server_default=sa.text("'pending'")),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()')),
    )


def downgrade():
    op.drop_table('trade_offers')
    op.drop_table('trade_listings')
    op.drop_table('user_sprites')
    op.drop_table('sprites')
